# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('upassword', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('uaddressee', models.CharField(max_length=30)),
                ('ushipping_address', models.CharField(max_length=100)),
                ('uzip_code', models.CharField(max_length=6)),
                ('uphone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
